### PR TITLE
Fix GitHub spelling

### PR DESCRIPTION
**Pull request by friederbluemle**
`Github` -> `GitHub`

It would be great if you could fix it on the Chrome Web Store description as well. Thanks for this useful extension @softvar 👍

### CODE REVIEW

**Comment by friederbluemle** [comment]
Rebased onto latest `master` branch.

**Comment by softvar** [comment]
Hey @friederbluemle , apologies for the late reply. COuld you please rebase your branch with current master branch? Will merge this branch post that.
Thanks @friederbluemle  👍

**Comment by friederbluemle** [comment]
@softvar Sure thing, rebased and resolved conflicts! 👌

**Comment by softvar** [comment]
Thanks, @friederbluemle for noticing and fixing. 👍

**Pull request merged**
