### PR TITLE
Support Firefox & Edge [WIP] [DON'T MERGE]

### PR DESCRIPTION
**Pull request by berwyn**
This is a work-in-progress to add support for WebExtensions platforms like Firefox and Edge.

I'm opening the pull request early as a progress tracker, and hopefully to ensure that other developers don't accidentally duplicate effort. I'll be sure to update it when it's ready to merge :)

### CODE REVIEW

**Comment by softvar** [comment]
This is a nice initiative. Thanks for owning it up! 👍

**Comment by softvar** [comment]
Hey,

Any updates?

**Comment by berwyn** [comment]
Sorry, haven't had nearly as much time to work on this as I thought I would! It's still something I'd like to do, though.

**Comment by softvar** [comment]
Hey @berwyn 
Let me know if you need any help from me. Would like to discuss it further :)

**Comment by berwyn** [comment]
Hey, sorry to procrastinate this again! Ended up having a crazy June and then moved countries :V

Last time I was working on this, Edge wasn't wanting to load the content script and it's something I never got a chance to circle back around to. If someone else wants to take this up, I'm more than happy to hand it off, but otherwise my time might be sparse for a few months more :/

**Comment by RaspberryPiFan** [comment]
Soon Edge is no problem anymore, it will use Chromium and support this extension

**Pull request closed without merging**
